services:
  app:
    container_name: user-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - gradle-cache:/root/.gradle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    container_name: user-db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=danworldman
      - POSTGRES_PASSWORD=user
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U danworldman -d user_db" ]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    container_name: user-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db-data:
  gradle-cache: