spring:
  datasource:
    url: jdbc:postgresql://db:5432/user_db
    username: danworldman
    password: user
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379