spring:
  application:
    name: user-service
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: local